export const habit = [
  {
    id: 1,
    name: "Meditate",
    repeat: "Daily",
    goal: "1 Times Daily",
    timeofday: "Any Time",
    startdate: "Today",
    url: "https://metro.co.uk/wp-content/uploads/2021/01/GettyImages-1217697475.jpg?quality=90&strip=all",
  },
  {
    id: 2,
    name: "Yoga",
    repeat: "Daily",
    goal: "1 Times Daily",
    timeofday: "Any Time",
    startdate: "Today",
    url: "https://cdn4.vectorstock.com/i/1000x1000/05/83/a-hipster-man-practicing-yoga-on-nature-background-vector-34900583.jpg",
  },
  {
    id: 3,
    name: "Running",
    repeat: "Daily",
    goal: "1 Times Daily",
    timeofday: "Any Time",
    startdate: "Today",
    url: "https://media.self.com/photos/61bb7bd3f9b246956c823a8b/4:3/w_2560%2Cc_limit/GettyImages-1304862992.jpeg",
  },
  {
    id: 4,
    name: "Read Books",
    repeat: "Daily",
    goal: "1 Times Daily",
    timeofday: "Any Time",
    startdate: "Today",
    url: "https://img.freepik.com/free-vector/hand-drawn-flat-design-stack-books_23-2149342941.jpg?w=2000",
  },
  {
    id: 5,
    name: "Drinking Water",
    repeat: "Daily",
    goal: "1 Times Daily",
    timeofday: "Any Time",
    startdate: "Today",
    url: "https://blog.drinkhint.com/wp-content/uploads/2016/06/TheQuench_WaterApps_JadePurpleBrown_1000x667.jpg",
  },
];
